### PR TITLE
Improved cache tests

### PR DESCRIPTION
**Pull request by hassler-d**
Changed caching strategy in `TokenKeyServiceWithCache`

### CODE REVIEW

**Comment by nenaraab** [comment]
@mwdb this belongs to the mail from last week. Please have a final look at it.

**Comment by nenaraab** [comment]
@mwdb can you please have a look at it, the details were provided to you via mail. 
Thanks!

**Comment by nenaraab** [comment]
@hassler-d 

please adapt the configuration:
- reduce time to 10 minutes

and we have to clarify with Patrick , whether is a delay given, until the new token key is used for token creation...

**Comment by hassler-d** [comment]
> @hassler-d
> 
> please adapt the configuration:
> 
> * reduce time to 10 minutes

Was already at 10 minutes. However, the comment explaining the value was not correct. I changed that.

**Pull request merged**
