### PR TITLE
Made the logon optional in case one already logged on

### PR DESCRIPTION
**Pull request by Essenpreis**
@alstolten. CF CLi stores an access token locally after a logon. The idea is maximum reuse over days. The script in current form forced the user to re-logon every time aborting existing logons. I changed the script so it will ask before executing a new log on.
Please review and tell me or @mwdb to merge it.

### CODE REVIEW

**Comment by alstolten** [comment]
@Essenpreis great idea, thank you for the contribution! Will check if I can make this available for the bash script also.

**Comment by nenaraab** [comment]
@Essenpreis please sign the Contributor Licence Agreement :-) Thanks!

**Comment by Essenpreis** [comment]
@alstolten . Finalized the version. Wdyt? Want to give me a review?

**Comment by alstolten** [comment]
Hi @Essenpreis looks good for me. I believe you still need to sign the CLA to be able to contribute. Before we could merge we then need the tests to be fixed, but that is not related to the logcollector.

**Pull request merged**
