### PR TITLE
return null when token claim is not present

### LINKED ISSUE #910: Wrong return value in XsuaaToken with multiple attributes
Hi Team,

it seams like the behaviour of `Token.getXSUserAttribute(String attributeName)` is broken for a `XsuaaToken` with more than one attribute.
According to the documentation this method should return:
> the attribute values array or null if there exists no such attribute

However,  if another attribute exists in the token besides the requested one, the method returns an empty array instead of null.

In the following there is a Controller and its Test, which illustrates the problem.

Best regards,
Alex

```java
import com.sap.cloud.security.xsuaa.token.XsuaaToken;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class Example {

    @GetMapping(value = "/example")
    public String example(@AuthenticationPrincipal XsuaaToken token) {
        String[] countries = token.getXSUserAttribute("country");
        String[] costCenters = token.getXSUserAttribute("costCenter");

        String[] output = new String[2];
        if (costCenters != null) {
            output[0] = "costCenters: " + String.join(", ", costCenters);
        }

        if (countries != null) {
            output[1] = "countries: " + String.join(", ", countries);
        }

        return String.join("\n", output);
    }
}
```

In these tests exampleSingle() fails unexpectedly.

```java
import com.sap.cloud.security.json.DefaultJsonObject;
import com.sap.cloud.security.test.api.SecurityTestContext;
import com.sap.cloud.security.test.extension.XsuaaExtension;
import com.sap.cloud.security.token.TokenClaims;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpHeaders;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.RequestPostProcessor;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {"xsuaa.xsappname=xsapp!t0815","xsuaa.clientid=sb-clientId!t0815", "xsuaa.url=http://localhost","xsuaa.uaadomain=localhost"})
@AutoConfigureMockMvc
@ExtendWith(XsuaaExtension.class)
public class ExampleTest {

    @Autowired
    private MockMvc mvc;

    private String jwtBoth;
    private String jwtSingle;
    private String jwtNone;
    private String jwtEmpty;

    @BeforeEach
    public void setup(SecurityTestContext securityTest) {
        DefaultJsonObject bothAttributes = new DefaultJsonObject("{\"costCenter\": [\"0815\"],\"country\": [\"DE\"]}");
        DefaultJsonObject singleAttribute = new DefaultJsonObject("{\"costCenter\": [\"0815\"]}");
        DefaultJsonObject emptyAttributes = new DefaultJsonObject("{\"costCenter\": [], \"country\": []}");

        jwtBoth = securityTest.getPreconfiguredJwtGenerator()
                .withClaimValue(TokenClaims.XSUAA.XS_USER_ATTRIBUTES, bothAttributes)
                .createToken().getTokenValue();

        jwtSingle = securityTest.getPreconfiguredJwtGenerator()
                .withClaimValue(TokenClaims.XSUAA.XS_USER_ATTRIBUTES, singleAttribute)
                .createToken().getTokenValue();

        jwtNone = securityTest.getPreconfiguredJwtGenerator()
                .createToken().getTokenValue();

        jwtEmpty = securityTest.getPreconfiguredJwtGenerator()
                .withClaimValue(TokenClaims.XSUAA.XS_USER_ATTRIBUTES, emptyAttributes)
                .createToken().getTokenValue();
    }

    @Test
    public void exampleBoth() throws Exception {
        String response = mvc
                .perform(get("/example")
                        .with(bearerToken(jwtBoth)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();

        Assertions.assertEquals("costCenters: 0815\ncountries: DE", response);
    }

    @Test
    public void exampleNone() throws Exception {
        String response = mvc
                .perform(get("/example")
                        .with(bearerToken(jwtNone)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();

        Assertions.assertEquals("null\nnull", response);
    }

    @Test
    public void exampleEmpty() throws Exception {
        String response = mvc
                .perform(get("/example")
                        .with(bearerToken(jwtEmpty)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();

        Assertions.assertEquals("costCenters: \ncountries: ", response);
    }

    @Test
    public void exampleSingle() throws Exception {
        String response = mvc
                .perform(get("/example")
                        .with(bearerToken(jwtSingle)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();

        Assertions.assertEquals("costCenters: 0815\nnull", response);
    }

    static BearerTokenRequestPostProcessor bearerToken(String token) {
        return new BearerTokenRequestPostProcessor(token);
    }

    private static class BearerTokenRequestPostProcessor implements RequestPostProcessor {
        private String token;

        public BearerTokenRequestPostProcessor(String token) {
            this.token = token;
        }

        @Override
        public MockHttpServletRequest postProcessRequest(MockHttpServletRequest request) {
            request.addHeader(HttpHeaders.AUTHORIZATION, "Bearer " + this.token);
            return request;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by liga-oz**
closes #910

### CODE REVIEW

**Comment by nenaraab** [comment]
@liga-oz thanks for the fix, can you please document the change in the CHANGELOG.md as it may lead to incompatibilities for our consumers.

**Review by nenaraab — COMMENTED** [review]
Hi @liga-oz could you please do me a favour and evaluate whether the code or the javadoc is wrong. With this code change `NullPointerExceptions` may occur on customers applications side, when we update the behaviour.

**Comment by liga-oz** [comment]
> Hi @liga-oz could you please do me a favour and evaluate whether the code or the javadoc is wrong. With this code change `NullPointerExceptions` may occur on customers applications side, when we update the behaviour.

Previously `null` was never returned instead empty array was returned, but javadoc and `@Nullable` annotation on interface level indicated that it can be `null`, so I presume that application users should have considered the fact that the `null` might be returned. We can change the annotation and javadoc which have been there since last year, but here for example it is actually considered to be `null`: https://github.com/SAP/cloud-security-xsuaa-integration/blob/b6003b7e77262c122cfaef8efe0bbd820e56bfe3/java-security/src/main/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapter.java#L410 

so I would guess that this bug should be fixed to return null values instead of empty array.

**Review by nenaraab — CHANGES_REQUESTED** [review]
As discussed:
- spring-xsuaa `Token` interface may return null in case attribute van't be found acccording to its javadoc
- `XsuaaTokenComp` need to fullfill legacy spring-xsuaa Token interface
- but in `java-api` Token interface and all its implementations such as  `XSUserInfoAdapter` we remain with empty List and need hopefully only to adapt the javadoc.

**Review by nenaraab — APPROVED** [review]

**Pull request merged**
