### PR TITLE
Better configurability for JwtGenerator

### PR DESCRIPTION
**Pull request by ttrabold**
* Make Header extensible
* Make createFromClaims accessible
* Introduce TokenHeaders class (similarly to TokenClaims)

### CODE REVIEW

**Comment by ttrabold** [comment]
@nenaraab As discussed, we made a few changes for the JwtGenerator class to better suit our needs while still remaining compatible.

**Comment by nenaraab** [comment]
@ttrabold 
Thanks for the PR. Please sign SAP Contributor Licence :-)

**Comment by ttrabold** [comment]
I already did but nothing happens. I will try to close the PR and reopen it.

**Comment by ttrabold** [comment]
Still not working. @nenaraab

**Comment by ttrabold** [comment]
We figured it out. Markus needs to sign too as we were using a pairing station with git duet.

**Comment by ttrabold** [comment]
@nenaraab ready to go now ;)

**Pull request merged**
